name: Bump Build Number
on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  bump-build-number:
    uses: salva133/My-Workflows/.github/workflows/bump-build-number.yml@91a31c01990c581dc0f86b57f08374764feb1702
